### ISSUE TITLE
Calling <<-EOS.undent is deprecated!

### ISSUE THREAD

**Issue by dericed** [mediamicroservices/homebrew-mm#13]
```
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/mediamicroservices/homebrew-mm/mm.rb:90:in `caveats'
Please report this to the mediamicroservices/mm tap!
```

Related patch: https://github.com/mediamicroservices/homebrew-mm/pull/12

re-opened from https://github.com/mediamicroservices/homebrew-mm/issues/11

**Comment by CSchloss385** [comment]
Changed <<-EOS.undet to <<~EOS and this appears to fix the problem.
